#include "font.h"
#define STB_IMAGE_IMPLEMENTATION
#define STBI_ONLY_PNG
#define STBI_NO_STDIO
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wsign-conversion"
#include "stb_image.h"
#pragma GCC diagnostic pop
#include <string.h>

/* Embedded MTSDF atlas (generated at build time from the baked PNG) */
#include "inter-msdf.png.h"
/* Per-glyph metrics (generated by scripts/generate-font-atlas.py) */
#include "font_metrics.h"

float font_load_atlas(uint8_t *rgba_out, font_glyph *glyphs_out,
                      float *px_range_out) {
    memcpy(glyphs_out, font_metrics, sizeof(font_metrics));
    if (px_range_out) *px_range_out = FONT_MSDF_RANGE;

    int w = 0, h = 0, comp = 0;
    unsigned char *pixels = stbi_load_from_memory(
        inter_msdf_png, (int)inter_msdf_png_len, &w, &h, &comp, 4);
    if (!pixels || w != FONT_ATLAS_SIZE || h != FONT_ATLAS_SIZE) {
        /* Fallback: blank atlas — every fragment lands outside the
         * distance field and gets discarded, so text is simply absent. */
        if (pixels) stbi_image_free(pixels);
        memset(rgba_out, 0, (size_t)FONT_ATLAS_SIZE * FONT_ATLAS_SIZE * 4);
        return FONT_MSDF_SIZE;
    }

    memcpy(rgba_out, pixels, (size_t)FONT_ATLAS_SIZE * FONT_ATLAS_SIZE * 4);
    stbi_image_free(pixels);
    return FONT_MSDF_SIZE;
}
