/* Auto-generated by icons/generate.js — do not edit. */
#ifndef ARPENTRY_ICON_MAP_H
#define ARPENTRY_ICON_MAP_H

#include <string.h>

#define ICON_FIRST_CODEPOINT 0xE000
#define ICON_COUNT 20

static const struct {
    const char *name;
    int codepoint;
} icon_map[ICON_COUNT] = {
    {"marker", 0xE000},
    {"town-hall", 0xE001},
    {"library", 0xE002},
    {"grocery", 0xE003},
    {"park", 0xE004},
    {"school", 0xE005},
    {"rail", 0xE006},
    {"hospital", 0xE007},
    {"museum", 0xE008},
    {"restaurant", 0xE009},
    {"cafe", 0xE00A},
    {"bar", 0xE00B},
    {"bank", 0xE00C},
    {"fuel", 0xE00D},
    {"parking", 0xE00E},
    {"place-of-worship", 0xE00F},
    {"fire-station", 0xE010},
    {"police", 0xE011},
    {"post", 0xE012},
    {"swimming", 0xE013},
};

#endif /* ARPENTRY_ICON_MAP_H */
