#!/usr/bin/env node
/**
 * generate.js — Convert Maki SVG icons into a TrueType font
 * and a C header mapping icon names to glyph indices.
 *
 * Usage:
 *   cd icons && npm install && npm run generate
 *
 * Outputs:
 *   ../client/assets/maki-icons.ttf   — TrueType font with icon glyphs
 *   ../client/src/icon_map.h          — C header: icon name → glyph index
 *
 * Icons are assigned Unicode codepoints in the Private Use Area (U+E000+).
 * The C header provides a lookup function icon_find(name) → index.
 */

const fs = require("fs");
const path = require("path");
const { Readable } = require("stream");
const { SVGIcons2SVGFontStream } = require("svgicons2svgfont");
const svg2ttf = require("svg2ttf");

/* Icons to include (subset of Maki). Add more as needed. */
const ICON_NAMES = [
  "marker",
  "town-hall",
  "library",
  "grocery",
  "park",
  "school",
  "rail",
  "hospital",
  "museum",
  "restaurant",
  "cafe",
  "bar",
  "bank",
  "fuel",
  "parking",
  "place-of-worship",
  "fire-station",
  "police",
  "post",
  "swimming",
];

const MAKI_BASE_URL =
  "https://raw.githubusercontent.com/mapbox/maki/main/icons";
const FIRST_CODEPOINT = 0xe000;
const ROOT = path.join(__dirname, "..");
const OUT_TTF = path.join(ROOT, "client", "assets", "maki-icons.ttf");
const OUT_HEADER = path.join(ROOT, "client", "src", "icon_map.h");

async function fetchSvg(name) {
  const url = `${MAKI_BASE_URL}/${name}.svg`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
  return await res.text();
}

async function main() {
  console.log(`Fetching ${ICON_NAMES.length} Maki icons...`);

  /* Download SVGs */
  const svgs = [];
  for (const name of ICON_NAMES) {
    try {
      const svg = await fetchSvg(name);
      svgs.push({ name, svg });
      console.log(`  ✓ ${name}`);
    } catch (e) {
      console.warn(`  ✗ ${name}: ${e.message}`);
    }
  }

  if (svgs.length === 0) {
    console.error("No icons fetched, aborting.");
    process.exit(1);
  }

  /* Generate SVG font */
  console.log("Generating SVG font...");
  const svgFont = await new Promise((resolve, reject) => {
    const chunks = [];
    const fontStream = new SVGIcons2SVGFontStream({
      fontName: "maki-icons",
      fontHeight: 1000,
      normalize: true,
    });
    fontStream.on("data", (chunk) => chunks.push(typeof chunk === "string" ? chunk : chunk.toString()));
    fontStream.on("end", () => resolve(chunks.join("")));
    fontStream.on("error", reject);

    for (let i = 0; i < svgs.length; i++) {
      const { name, svg } = svgs[i];
      const codepoint = FIRST_CODEPOINT + i;
      const glyph = new Readable();
      glyph._read = function () {};
      glyph.push(svg);
      glyph.push(null);
      glyph.metadata = {
        name,
        unicode: [String.fromCodePoint(codepoint)],
      };
      fontStream.write(glyph);
    }
    fontStream.end();
  });

  /* Convert to TTF */
  console.log("Converting to TTF...");
  const ttf = svg2ttf(svgFont, {});
  const ttfBuf = Buffer.from(ttf.buffer);

  /* Write TTF */
  fs.mkdirSync(path.dirname(OUT_TTF), { recursive: true });
  fs.writeFileSync(OUT_TTF, ttfBuf);
  console.log(`Wrote ${OUT_TTF} (${ttfBuf.length} bytes)`);

  /* Generate C header */
  const entries = svgs.map((s, i) => ({
    name: s.name,
    codepoint: FIRST_CODEPOINT + i,
    index: i,
  }));

  let header = `/* Auto-generated by icons/generate.js — do not edit. */
#ifndef ARPENTRY_ICON_MAP_H
#define ARPENTRY_ICON_MAP_H

#include <string.h>

#define ICON_FIRST_CODEPOINT 0xE000
#define ICON_COUNT ${entries.length}

static const struct {
    const char *name;
    int codepoint;
} icon_map[ICON_COUNT] = {
`;

  for (const e of entries) {
    header += `    {"${e.name}", 0x${e.codepoint.toString(16).toUpperCase()}},\n`;
  }

  header += `};

#endif /* ARPENTRY_ICON_MAP_H */
`;

  fs.mkdirSync(path.dirname(OUT_HEADER), { recursive: true });
  fs.writeFileSync(OUT_HEADER, header);
  console.log(`Wrote ${OUT_HEADER} (${entries.length} icons)`);

  console.log("Done!");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
