// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use crate::tile_generated::*;
use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod arpentry {

  use crate::tile_generated::*;
  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod tiles {

  use crate::tile_generated::*;
  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum ModelOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Model<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Model<'a> {
  type Inner = Model<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Model<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_X: flatbuffers::VOffsetT = 6;
  pub const VT_Y: flatbuffers::VOffsetT = 8;
  pub const VT_Z: flatbuffers::VOffsetT = 10;
  pub const VT_W: flatbuffers::VOffsetT = 12;
  pub const VT_INDICES: flatbuffers::VOffsetT = 14;
  pub const VT_NORMALS: flatbuffers::VOffsetT = 16;
  pub const VT_PARTS: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Model { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ModelArgs<'args>
  ) -> flatbuffers::WIPOffset<Model<'bldr>> {
    let mut builder = ModelBuilder::new(_fbb);
    if let Some(x) = args.parts { builder.add_parts(x); }
    if let Some(x) = args.normals { builder.add_normals(x); }
    if let Some(x) = args.indices { builder.add_indices(x); }
    if let Some(x) = args.w { builder.add_w(x); }
    if let Some(x) = args.z { builder.add_z(x); }
    if let Some(x) = args.y { builder.add_y(x); }
    if let Some(x) = args.x { builder.add_x(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Model::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn x(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(Model::VT_X, None).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(Model::VT_Y, None).unwrap()}
  }
  #[inline]
  pub fn z(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(Model::VT_Z, None).unwrap()}
  }
  #[inline]
  pub fn w(&self) -> Option<flatbuffers::Vector<'a, u16>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(Model::VT_W, None)}
  }
  #[inline]
  pub fn indices(&self) -> flatbuffers::Vector<'a, u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(Model::VT_INDICES, None).unwrap()}
  }
  #[inline]
  pub fn normals(&self) -> Option<flatbuffers::Vector<'a, i8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i8>>>(Model::VT_NORMALS, None)}
  }
  #[inline]
  pub fn parts(&self) -> Option<flatbuffers::Vector<'a, Part>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Part>>>(Model::VT_PARTS, None)}
  }
}

impl flatbuffers::Verifiable for Model<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("x", Self::VT_X, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("y", Self::VT_Y, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("z", Self::VT_Z, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("w", Self::VT_W, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("indices", Self::VT_INDICES, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i8>>>("normals", Self::VT_NORMALS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Part>>>("parts", Self::VT_PARTS, false)?
     .finish();
    Ok(())
  }
}
pub struct ModelArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub w: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub indices: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub normals: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i8>>>,
    pub parts: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Part>>>,
}
impl<'a> Default for ModelArgs<'a> {
  #[inline]
  fn default() -> Self {
    ModelArgs {
      name: None, // required field
      x: None, // required field
      y: None, // required field
      z: None, // required field
      w: None,
      indices: None, // required field
      normals: None,
      parts: None,
    }
  }
}

pub struct ModelBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ModelBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_NAME, name);
  }
  #[inline]
  pub fn add_x(&mut self, x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_X, x);
  }
  #[inline]
  pub fn add_y(&mut self, y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_Y, y);
  }
  #[inline]
  pub fn add_z(&mut self, z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_Z, z);
  }
  #[inline]
  pub fn add_w(&mut self, w: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_W, w);
  }
  #[inline]
  pub fn add_indices(&mut self, indices: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_INDICES, indices);
  }
  #[inline]
  pub fn add_normals(&mut self, normals: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_NORMALS, normals);
  }
  #[inline]
  pub fn add_parts(&mut self, parts: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Part>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Model::VT_PARTS, parts);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ModelBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ModelBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Model<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Model::VT_NAME,"name");
    self.fbb_.required(o, Model::VT_X,"x");
    self.fbb_.required(o, Model::VT_Y,"y");
    self.fbb_.required(o, Model::VT_Z,"z");
    self.fbb_.required(o, Model::VT_INDICES,"indices");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Model<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Model");
      ds.field("name", &self.name());
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.field("w", &self.w());
      ds.field("indices", &self.indices());
      ds.field("normals", &self.normals());
      ds.field("parts", &self.parts());
      ds.finish()
  }
}
pub enum ModelLibraryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ModelLibrary<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ModelLibrary<'a> {
  type Inner = ModelLibrary<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ModelLibrary<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_MODELS: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ModelLibrary { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ModelLibraryArgs<'args>
  ) -> flatbuffers::WIPOffset<ModelLibrary<'bldr>> {
    let mut builder = ModelLibraryBuilder::new(_fbb);
    if let Some(x) = args.models { builder.add_models(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(ModelLibrary::VT_VERSION, Some(1)).unwrap()}
  }
  #[inline]
  pub fn models(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Model<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Model>>>>(ModelLibrary::VT_MODELS, None)}
  }
}

impl flatbuffers::Verifiable for ModelLibrary<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u16>("version", Self::VT_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Model>>>>("models", Self::VT_MODELS, false)?
     .finish();
    Ok(())
  }
}
pub struct ModelLibraryArgs<'a> {
    pub version: u16,
    pub models: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Model<'a>>>>>,
}
impl<'a> Default for ModelLibraryArgs<'a> {
  #[inline]
  fn default() -> Self {
    ModelLibraryArgs {
      version: 1,
      models: None,
    }
  }
}

pub struct ModelLibraryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ModelLibraryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u16) {
    self.fbb_.push_slot::<u16>(ModelLibrary::VT_VERSION, version, 1);
  }
  #[inline]
  pub fn add_models(&mut self, models: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Model<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ModelLibrary::VT_MODELS, models);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ModelLibraryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ModelLibraryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ModelLibrary<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ModelLibrary<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ModelLibrary");
      ds.field("version", &self.version());
      ds.field("models", &self.models());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `ModelLibrary`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_model_library_unchecked`.
pub fn root_as_model_library(buf: &[u8]) -> Result<ModelLibrary, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<ModelLibrary>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `ModelLibrary` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_model_library_unchecked`.
pub fn size_prefixed_root_as_model_library(buf: &[u8]) -> Result<ModelLibrary, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<ModelLibrary>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `ModelLibrary` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_model_library_unchecked`.
pub fn root_as_model_library_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ModelLibrary<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<ModelLibrary<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `ModelLibrary` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_model_library_unchecked`.
pub fn size_prefixed_root_as_model_library_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<ModelLibrary<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<ModelLibrary<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a ModelLibrary and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `ModelLibrary`.
pub unsafe fn root_as_model_library_unchecked(buf: &[u8]) -> ModelLibrary {
  flatbuffers::root_unchecked::<ModelLibrary>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed ModelLibrary and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `ModelLibrary`.
pub unsafe fn size_prefixed_root_as_model_library_unchecked(buf: &[u8]) -> ModelLibrary {
  flatbuffers::size_prefixed_root_unchecked::<ModelLibrary>(buf)
}
pub const MODEL_LIBRARY_IDENTIFIER: &str = "arpm";

#[inline]
pub fn model_library_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, MODEL_LIBRARY_IDENTIFIER, false)
}

#[inline]
pub fn model_library_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, MODEL_LIBRARY_IDENTIFIER, true)
}

pub const MODEL_LIBRARY_EXTENSION: &str = "arpm";

#[inline]
pub fn finish_model_library_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<ModelLibrary<'a>>) {
  fbb.finish(root, Some(MODEL_LIBRARY_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_model_library_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<ModelLibrary<'a>>) {
  fbb.finish_size_prefixed(root, Some(MODEL_LIBRARY_IDENTIFIER));
}
}  // pub mod tiles
}  // pub mod arpentry

