// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod arpentry {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod tiles {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_LAYER_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_LAYER_TYPE: u8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_LAYER_TYPE: [LayerType; 7] = [
  LayerType::Terrain,
  LayerType::Texture,
  LayerType::Extrusion,
  LayerType::Instance,
  LayerType::Label,
  LayerType::Line,
  LayerType::LineLabel,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct LayerType(pub u8);
#[allow(non_upper_case_globals)]
impl LayerType {
  pub const Terrain: Self = Self(0);
  pub const Texture: Self = Self(1);
  pub const Extrusion: Self = Self(2);
  pub const Instance: Self = Self(3);
  pub const Label: Self = Self(4);
  pub const Line: Self = Self(5);
  pub const LineLabel: Self = Self(6);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Terrain,
    Self::Texture,
    Self::Extrusion,
    Self::Instance,
    Self::Label,
    Self::Line,
    Self::LineLabel,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Terrain => Some("Terrain"),
      Self::Texture => Some("Texture"),
      Self::Extrusion => Some("Extrusion"),
      Self::Instance => Some("Instance"),
      Self::Label => Some("Label"),
      Self::Line => Some("Line"),
      Self::LineLabel => Some("LineLabel"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for LayerType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for LayerType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for LayerType {
    type Output = LayerType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for LayerType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for LayerType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for LayerType {}
// struct RGBA, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct RGBA(pub [u8; 4]);
impl Default for RGBA { 
  fn default() -> Self { 
    Self([0; 4])
  }
}
impl core::fmt::Debug for RGBA {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("RGBA")
      .field("r", &self.r())
      .field("g", &self.g())
      .field("b", &self.b())
      .field("a", &self.a())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for RGBA {}
impl<'a> flatbuffers::Follow<'a> for RGBA {
  type Inner = &'a RGBA;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a RGBA>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a RGBA {
  type Inner = &'a RGBA;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<RGBA>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for RGBA {
    type Output = RGBA;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const RGBA as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for RGBA {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> RGBA {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    r: u8,
    g: u8,
    b: u8,
    a: u8,
  ) -> Self {
    let mut s = Self([0; 4]);
    s.set_r(r);
    s.set_g(g);
    s.set_b(b);
    s.set_a(a);
    s
  }

  pub fn r(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_r(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn g(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[1..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_g(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[1..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn b(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_b(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn a(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[3..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_a(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[3..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum PaintEntryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PaintEntry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PaintEntry<'a> {
  type Inner = PaintEntry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PaintEntry<'a> {
  pub const VT_CLASS: flatbuffers::VOffsetT = 4;
  pub const VT_COLOR: flatbuffers::VOffsetT = 6;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 8;
  pub const VT_MODEL: flatbuffers::VOffsetT = 10;
  pub const VT_MIN_SCALE: flatbuffers::VOffsetT = 12;
  pub const VT_MAX_SCALE: flatbuffers::VOffsetT = 14;
  pub const VT_RANDOM_YAW: flatbuffers::VOffsetT = 16;
  pub const VT_RANDOM_SCALE: flatbuffers::VOffsetT = 18;
  pub const VT_MIN_LEVEL: flatbuffers::VOffsetT = 20;
  pub const VT_CASING_COLOR: flatbuffers::VOffsetT = 22;
  pub const VT_CASING_WIDTH: flatbuffers::VOffsetT = 24;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PaintEntry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PaintEntryArgs<'args>
  ) -> flatbuffers::WIPOffset<PaintEntry<'bldr>> {
    let mut builder = PaintEntryBuilder::new(_fbb);
    builder.add_casing_width(args.casing_width);
    if let Some(x) = args.casing_color { builder.add_casing_color(x); }
    builder.add_max_scale(args.max_scale);
    builder.add_min_scale(args.min_scale);
    if let Some(x) = args.model { builder.add_model(x); }
    builder.add_width(args.width);
    if let Some(x) = args.color { builder.add_color(x); }
    if let Some(x) = args.class { builder.add_class(x); }
    builder.add_min_level(args.min_level);
    builder.add_random_scale(args.random_scale);
    builder.add_random_yaw(args.random_yaw);
    builder.finish()
  }


  #[inline]
  pub fn class(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PaintEntry::VT_CLASS, None).unwrap()}
  }
  #[inline]
  pub fn color(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(PaintEntry::VT_COLOR, None)}
  }
  #[inline]
  pub fn width(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(PaintEntry::VT_WIDTH, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn model(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(PaintEntry::VT_MODEL, None)}
  }
  #[inline]
  pub fn min_scale(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(PaintEntry::VT_MIN_SCALE, Some(1.0)).unwrap()}
  }
  #[inline]
  pub fn max_scale(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(PaintEntry::VT_MAX_SCALE, Some(1.0)).unwrap()}
  }
  #[inline]
  pub fn random_yaw(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PaintEntry::VT_RANDOM_YAW, Some(true)).unwrap()}
  }
  #[inline]
  pub fn random_scale(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PaintEntry::VT_RANDOM_SCALE, Some(true)).unwrap()}
  }
  #[inline]
  pub fn min_level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(PaintEntry::VT_MIN_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn casing_color(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(PaintEntry::VT_CASING_COLOR, None)}
  }
  #[inline]
  pub fn casing_width(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(PaintEntry::VT_CASING_WIDTH, Some(0.0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for PaintEntry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("class", Self::VT_CLASS, true)?
     .visit_field::<RGBA>("color", Self::VT_COLOR, false)?
     .visit_field::<f32>("width", Self::VT_WIDTH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("model", Self::VT_MODEL, false)?
     .visit_field::<f32>("min_scale", Self::VT_MIN_SCALE, false)?
     .visit_field::<f32>("max_scale", Self::VT_MAX_SCALE, false)?
     .visit_field::<bool>("random_yaw", Self::VT_RANDOM_YAW, false)?
     .visit_field::<bool>("random_scale", Self::VT_RANDOM_SCALE, false)?
     .visit_field::<u8>("min_level", Self::VT_MIN_LEVEL, false)?
     .visit_field::<RGBA>("casing_color", Self::VT_CASING_COLOR, false)?
     .visit_field::<f32>("casing_width", Self::VT_CASING_WIDTH, false)?
     .finish();
    Ok(())
  }
}
pub struct PaintEntryArgs<'a> {
    pub class: Option<flatbuffers::WIPOffset<&'a str>>,
    pub color: Option<&'a RGBA>,
    pub width: f32,
    pub model: Option<flatbuffers::WIPOffset<&'a str>>,
    pub min_scale: f32,
    pub max_scale: f32,
    pub random_yaw: bool,
    pub random_scale: bool,
    pub min_level: u8,
    pub casing_color: Option<&'a RGBA>,
    pub casing_width: f32,
}
impl<'a> Default for PaintEntryArgs<'a> {
  #[inline]
  fn default() -> Self {
    PaintEntryArgs {
      class: None, // required field
      color: None,
      width: 0.0,
      model: None,
      min_scale: 1.0,
      max_scale: 1.0,
      random_yaw: true,
      random_scale: true,
      min_level: 0,
      casing_color: None,
      casing_width: 0.0,
    }
  }
}

pub struct PaintEntryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PaintEntryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_class(&mut self, class: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PaintEntry::VT_CLASS, class);
  }
  #[inline]
  pub fn add_color(&mut self, color: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(PaintEntry::VT_COLOR, color);
  }
  #[inline]
  pub fn add_width(&mut self, width: f32) {
    self.fbb_.push_slot::<f32>(PaintEntry::VT_WIDTH, width, 0.0);
  }
  #[inline]
  pub fn add_model(&mut self, model: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PaintEntry::VT_MODEL, model);
  }
  #[inline]
  pub fn add_min_scale(&mut self, min_scale: f32) {
    self.fbb_.push_slot::<f32>(PaintEntry::VT_MIN_SCALE, min_scale, 1.0);
  }
  #[inline]
  pub fn add_max_scale(&mut self, max_scale: f32) {
    self.fbb_.push_slot::<f32>(PaintEntry::VT_MAX_SCALE, max_scale, 1.0);
  }
  #[inline]
  pub fn add_random_yaw(&mut self, random_yaw: bool) {
    self.fbb_.push_slot::<bool>(PaintEntry::VT_RANDOM_YAW, random_yaw, true);
  }
  #[inline]
  pub fn add_random_scale(&mut self, random_scale: bool) {
    self.fbb_.push_slot::<bool>(PaintEntry::VT_RANDOM_SCALE, random_scale, true);
  }
  #[inline]
  pub fn add_min_level(&mut self, min_level: u8) {
    self.fbb_.push_slot::<u8>(PaintEntry::VT_MIN_LEVEL, min_level, 0);
  }
  #[inline]
  pub fn add_casing_color(&mut self, casing_color: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(PaintEntry::VT_CASING_COLOR, casing_color);
  }
  #[inline]
  pub fn add_casing_width(&mut self, casing_width: f32) {
    self.fbb_.push_slot::<f32>(PaintEntry::VT_CASING_WIDTH, casing_width, 0.0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PaintEntryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PaintEntryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PaintEntry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PaintEntry::VT_CLASS,"class");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PaintEntry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PaintEntry");
      ds.field("class", &self.class());
      ds.field("color", &self.color());
      ds.field("width", &self.width());
      ds.field("model", &self.model());
      ds.field("min_scale", &self.min_scale());
      ds.field("max_scale", &self.max_scale());
      ds.field("random_yaw", &self.random_yaw());
      ds.field("random_scale", &self.random_scale());
      ds.field("min_level", &self.min_level());
      ds.field("casing_color", &self.casing_color());
      ds.field("casing_width", &self.casing_width());
      ds.finish()
  }
}
pub enum LayerStyleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LayerStyle<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LayerStyle<'a> {
  type Inner = LayerStyle<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> LayerStyle<'a> {
  pub const VT_SOURCE_LAYER: flatbuffers::VOffsetT = 4;
  pub const VT_TYPE_: flatbuffers::VOffsetT = 6;
  pub const VT_MIN_LEVEL: flatbuffers::VOffsetT = 8;
  pub const VT_PAINT: flatbuffers::VOffsetT = 10;
  pub const VT_TEXT_SIZE: flatbuffers::VOffsetT = 12;
  pub const VT_TEXT_COLOR: flatbuffers::VOffsetT = 14;
  pub const VT_TEXT_HALO_COLOR: flatbuffers::VOffsetT = 16;
  pub const VT_TEXT_HALO_WIDTH: flatbuffers::VOffsetT = 18;
  pub const VT_ICON_SIZE: flatbuffers::VOffsetT = 20;
  pub const VT_ICON_COLOR: flatbuffers::VOffsetT = 22;
  pub const VT_ICON_HALO_COLOR: flatbuffers::VOffsetT = 24;
  pub const VT_ICON_HALO_WIDTH: flatbuffers::VOffsetT = 26;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LayerStyle { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LayerStyleArgs<'args>
  ) -> flatbuffers::WIPOffset<LayerStyle<'bldr>> {
    let mut builder = LayerStyleBuilder::new(_fbb);
    builder.add_icon_halo_width(args.icon_halo_width);
    if let Some(x) = args.icon_halo_color { builder.add_icon_halo_color(x); }
    if let Some(x) = args.icon_color { builder.add_icon_color(x); }
    builder.add_icon_size(args.icon_size);
    builder.add_text_halo_width(args.text_halo_width);
    if let Some(x) = args.text_halo_color { builder.add_text_halo_color(x); }
    if let Some(x) = args.text_color { builder.add_text_color(x); }
    builder.add_text_size(args.text_size);
    if let Some(x) = args.paint { builder.add_paint(x); }
    if let Some(x) = args.source_layer { builder.add_source_layer(x); }
    builder.add_min_level(args.min_level);
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn source_layer(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(LayerStyle::VT_SOURCE_LAYER, None).unwrap()}
  }
  #[inline]
  pub fn type_(&self) -> LayerType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<LayerType>(LayerStyle::VT_TYPE_, Some(LayerType::Texture)).unwrap()}
  }
  #[inline]
  pub fn min_level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(LayerStyle::VT_MIN_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn paint(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PaintEntry<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PaintEntry>>>>(LayerStyle::VT_PAINT, None)}
  }
  #[inline]
  pub fn text_size(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(LayerStyle::VT_TEXT_SIZE, Some(14.0)).unwrap()}
  }
  #[inline]
  pub fn text_color(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(LayerStyle::VT_TEXT_COLOR, None)}
  }
  #[inline]
  pub fn text_halo_color(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(LayerStyle::VT_TEXT_HALO_COLOR, None)}
  }
  #[inline]
  pub fn text_halo_width(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(LayerStyle::VT_TEXT_HALO_WIDTH, Some(2.0)).unwrap()}
  }
  #[inline]
  pub fn icon_size(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(LayerStyle::VT_ICON_SIZE, Some(20.0)).unwrap()}
  }
  #[inline]
  pub fn icon_color(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(LayerStyle::VT_ICON_COLOR, None)}
  }
  #[inline]
  pub fn icon_halo_color(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(LayerStyle::VT_ICON_HALO_COLOR, None)}
  }
  #[inline]
  pub fn icon_halo_width(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(LayerStyle::VT_ICON_HALO_WIDTH, Some(0.5)).unwrap()}
  }
}

impl flatbuffers::Verifiable for LayerStyle<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("source_layer", Self::VT_SOURCE_LAYER, true)?
     .visit_field::<LayerType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<u8>("min_level", Self::VT_MIN_LEVEL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<PaintEntry>>>>("paint", Self::VT_PAINT, false)?
     .visit_field::<f32>("text_size", Self::VT_TEXT_SIZE, false)?
     .visit_field::<RGBA>("text_color", Self::VT_TEXT_COLOR, false)?
     .visit_field::<RGBA>("text_halo_color", Self::VT_TEXT_HALO_COLOR, false)?
     .visit_field::<f32>("text_halo_width", Self::VT_TEXT_HALO_WIDTH, false)?
     .visit_field::<f32>("icon_size", Self::VT_ICON_SIZE, false)?
     .visit_field::<RGBA>("icon_color", Self::VT_ICON_COLOR, false)?
     .visit_field::<RGBA>("icon_halo_color", Self::VT_ICON_HALO_COLOR, false)?
     .visit_field::<f32>("icon_halo_width", Self::VT_ICON_HALO_WIDTH, false)?
     .finish();
    Ok(())
  }
}
pub struct LayerStyleArgs<'a> {
    pub source_layer: Option<flatbuffers::WIPOffset<&'a str>>,
    pub type_: LayerType,
    pub min_level: u8,
    pub paint: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<PaintEntry<'a>>>>>,
    pub text_size: f32,
    pub text_color: Option<&'a RGBA>,
    pub text_halo_color: Option<&'a RGBA>,
    pub text_halo_width: f32,
    pub icon_size: f32,
    pub icon_color: Option<&'a RGBA>,
    pub icon_halo_color: Option<&'a RGBA>,
    pub icon_halo_width: f32,
}
impl<'a> Default for LayerStyleArgs<'a> {
  #[inline]
  fn default() -> Self {
    LayerStyleArgs {
      source_layer: None, // required field
      type_: LayerType::Texture,
      min_level: 0,
      paint: None,
      text_size: 14.0,
      text_color: None,
      text_halo_color: None,
      text_halo_width: 2.0,
      icon_size: 20.0,
      icon_color: None,
      icon_halo_color: None,
      icon_halo_width: 0.5,
    }
  }
}

pub struct LayerStyleBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LayerStyleBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_source_layer(&mut self, source_layer: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LayerStyle::VT_SOURCE_LAYER, source_layer);
  }
  #[inline]
  pub fn add_type_(&mut self, type_: LayerType) {
    self.fbb_.push_slot::<LayerType>(LayerStyle::VT_TYPE_, type_, LayerType::Texture);
  }
  #[inline]
  pub fn add_min_level(&mut self, min_level: u8) {
    self.fbb_.push_slot::<u8>(LayerStyle::VT_MIN_LEVEL, min_level, 0);
  }
  #[inline]
  pub fn add_paint(&mut self, paint: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<PaintEntry<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LayerStyle::VT_PAINT, paint);
  }
  #[inline]
  pub fn add_text_size(&mut self, text_size: f32) {
    self.fbb_.push_slot::<f32>(LayerStyle::VT_TEXT_SIZE, text_size, 14.0);
  }
  #[inline]
  pub fn add_text_color(&mut self, text_color: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(LayerStyle::VT_TEXT_COLOR, text_color);
  }
  #[inline]
  pub fn add_text_halo_color(&mut self, text_halo_color: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(LayerStyle::VT_TEXT_HALO_COLOR, text_halo_color);
  }
  #[inline]
  pub fn add_text_halo_width(&mut self, text_halo_width: f32) {
    self.fbb_.push_slot::<f32>(LayerStyle::VT_TEXT_HALO_WIDTH, text_halo_width, 2.0);
  }
  #[inline]
  pub fn add_icon_size(&mut self, icon_size: f32) {
    self.fbb_.push_slot::<f32>(LayerStyle::VT_ICON_SIZE, icon_size, 20.0);
  }
  #[inline]
  pub fn add_icon_color(&mut self, icon_color: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(LayerStyle::VT_ICON_COLOR, icon_color);
  }
  #[inline]
  pub fn add_icon_halo_color(&mut self, icon_halo_color: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(LayerStyle::VT_ICON_HALO_COLOR, icon_halo_color);
  }
  #[inline]
  pub fn add_icon_halo_width(&mut self, icon_halo_width: f32) {
    self.fbb_.push_slot::<f32>(LayerStyle::VT_ICON_HALO_WIDTH, icon_halo_width, 0.5);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LayerStyleBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LayerStyleBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LayerStyle<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LayerStyle::VT_SOURCE_LAYER,"source_layer");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LayerStyle<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LayerStyle");
      ds.field("source_layer", &self.source_layer());
      ds.field("type_", &self.type_());
      ds.field("min_level", &self.min_level());
      ds.field("paint", &self.paint());
      ds.field("text_size", &self.text_size());
      ds.field("text_color", &self.text_color());
      ds.field("text_halo_color", &self.text_halo_color());
      ds.field("text_halo_width", &self.text_halo_width());
      ds.field("icon_size", &self.icon_size());
      ds.field("icon_color", &self.icon_color());
      ds.field("icon_halo_color", &self.icon_halo_color());
      ds.field("icon_halo_width", &self.icon_halo_width());
      ds.finish()
  }
}
pub enum StyleOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Style<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Style<'a> {
  type Inner = Style<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Style<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_BACKGROUND: flatbuffers::VOffsetT = 8;
  pub const VT_LAYERS: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Style { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StyleArgs<'args>
  ) -> flatbuffers::WIPOffset<Style<'bldr>> {
    let mut builder = StyleBuilder::new(_fbb);
    if let Some(x) = args.layers { builder.add_layers(x); }
    if let Some(x) = args.background { builder.add_background(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Style::VT_VERSION, Some(1)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Style::VT_NAME, None)}
  }
  #[inline]
  pub fn background(&self) -> Option<&'a RGBA> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<RGBA>(Style::VT_BACKGROUND, None)}
  }
  #[inline]
  pub fn layers(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LayerStyle<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LayerStyle>>>>(Style::VT_LAYERS, None)}
  }
}

impl flatbuffers::Verifiable for Style<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u16>("version", Self::VT_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<RGBA>("background", Self::VT_BACKGROUND, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<LayerStyle>>>>("layers", Self::VT_LAYERS, false)?
     .finish();
    Ok(())
  }
}
pub struct StyleArgs<'a> {
    pub version: u16,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub background: Option<&'a RGBA>,
    pub layers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LayerStyle<'a>>>>>,
}
impl<'a> Default for StyleArgs<'a> {
  #[inline]
  fn default() -> Self {
    StyleArgs {
      version: 1,
      name: None,
      background: None,
      layers: None,
    }
  }
}

pub struct StyleBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StyleBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u16) {
    self.fbb_.push_slot::<u16>(Style::VT_VERSION, version, 1);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Style::VT_NAME, name);
  }
  #[inline]
  pub fn add_background(&mut self, background: &RGBA) {
    self.fbb_.push_slot_always::<&RGBA>(Style::VT_BACKGROUND, background);
  }
  #[inline]
  pub fn add_layers(&mut self, layers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<LayerStyle<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Style::VT_LAYERS, layers);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> StyleBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StyleBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Style<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Style<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Style");
      ds.field("version", &self.version());
      ds.field("name", &self.name());
      ds.field("background", &self.background());
      ds.field("layers", &self.layers());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Style`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_style_unchecked`.
pub fn root_as_style(buf: &[u8]) -> Result<Style, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Style>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Style` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_style_unchecked`.
pub fn size_prefixed_root_as_style(buf: &[u8]) -> Result<Style, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Style>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Style` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_style_unchecked`.
pub fn root_as_style_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Style<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Style<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Style` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_style_unchecked`.
pub fn size_prefixed_root_as_style_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Style<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Style<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Style and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Style`.
pub unsafe fn root_as_style_unchecked(buf: &[u8]) -> Style {
  flatbuffers::root_unchecked::<Style>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Style and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Style`.
pub unsafe fn size_prefixed_root_as_style_unchecked(buf: &[u8]) -> Style {
  flatbuffers::size_prefixed_root_unchecked::<Style>(buf)
}
pub const STYLE_IDENTIFIER: &str = "arps";

#[inline]
pub fn style_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, STYLE_IDENTIFIER, false)
}

#[inline]
pub fn style_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, STYLE_IDENTIFIER, true)
}

pub const STYLE_EXTENSION: &str = "arps";

#[inline]
pub fn finish_style_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Style<'a>>) {
  fbb.finish(root, Some(STYLE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_style_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Style<'a>>) {
  fbb.finish_size_prefixed(root, Some(STYLE_IDENTIFIER));
}
}  // pub mod tiles
}  // pub mod arpentry

