// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod arpentry {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod tiles {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_GEOMETRY_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_GEOMETRY_TYPE: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_GEOMETRY_TYPE: [GeometryType; 4] = [
  GeometryType::Point,
  GeometryType::Line,
  GeometryType::Polygon,
  GeometryType::Mesh,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct GeometryType(pub u8);
#[allow(non_upper_case_globals)]
impl GeometryType {
  pub const Point: Self = Self(0);
  pub const Line: Self = Self(1);
  pub const Polygon: Self = Self(2);
  pub const Mesh: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Point,
    Self::Line,
    Self::Polygon,
    Self::Mesh,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Point => Some("Point"),
      Self::Line => Some("Line"),
      Self::Polygon => Some("Polygon"),
      Self::Mesh => Some("Mesh"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for GeometryType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for GeometryType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for GeometryType {
    type Output = GeometryType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for GeometryType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for GeometryType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for GeometryType {}
// struct Bounds, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Bounds(pub [u8; 32]);
impl Default for Bounds { 
  fn default() -> Self { 
    Self([0; 32])
  }
}
impl core::fmt::Debug for Bounds {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Bounds")
      .field("west", &self.west())
      .field("south", &self.south())
      .field("east", &self.east())
      .field("north", &self.north())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Bounds {}
impl<'a> flatbuffers::Follow<'a> for Bounds {
  type Inner = &'a Bounds;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Bounds>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Bounds {
  type Inner = &'a Bounds;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Bounds>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Bounds {
    type Output = Bounds;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Bounds as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
    // Patched (flatc 24.3.25 omits this): align this f64 struct to 8 in the
    // builder so flatcc's verifier accepts the buffer. The struct stays
    // `repr(transparent)` (align 1) for the reader's `follow_cast_ref`.
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for Bounds {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Bounds {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    west: f64,
    south: f64,
    east: f64,
    north: f64,
  ) -> Self {
    let mut s = Self([0; 32]);
    s.set_west(west);
    s.set_south(south);
    s.set_east(east);
    s.set_north(north);
    s
  }

  pub fn west(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_west(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn south(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_south(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn east(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[16..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_east(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[16..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn north(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[24..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_north(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[24..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct ElevationRange, aligned to 8
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct ElevationRange(pub [u8; 16]);
impl Default for ElevationRange { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for ElevationRange {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("ElevationRange")
      .field("min", &self.min())
      .field("max", &self.max())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ElevationRange {}
impl<'a> flatbuffers::Follow<'a> for ElevationRange {
  type Inner = &'a ElevationRange;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a ElevationRange>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a ElevationRange {
  type Inner = &'a ElevationRange;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<ElevationRange>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for ElevationRange {
    type Output = ElevationRange;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const ElevationRange as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
    // Patched (flatc 24.3.25 omits this): align this f64 struct to 8 in the builder
    // so flatcc's verifier accepts the buffer; struct stays `repr(transparent)`.
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(8)
    }
}

impl<'a> flatbuffers::Verifiable for ElevationRange {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> ElevationRange {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    min: f64,
    max: f64,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_min(min);
    s.set_max(max);
    s
  }

  pub fn min(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_min(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn max(&self) -> f64 {
    let mut mem = core::mem::MaybeUninit::<<f64 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[8..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_max(&mut self, x: f64) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[8..].as_mut_ptr(),
        core::mem::size_of::<<f64 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum LayerInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LayerInfo<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LayerInfo<'a> {
  type Inner = LayerInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> LayerInfo<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_GEOMETRY_TYPES: flatbuffers::VOffsetT = 6;
  pub const VT_MIN_LEVEL: flatbuffers::VOffsetT = 8;
  pub const VT_MAX_LEVEL: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LayerInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LayerInfoArgs<'args>
  ) -> flatbuffers::WIPOffset<LayerInfo<'bldr>> {
    let mut builder = LayerInfoBuilder::new(_fbb);
    if let Some(x) = args.geometry_types { builder.add_geometry_types(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_max_level(args.max_level);
    builder.add_min_level(args.min_level);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(LayerInfo::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn geometry_types(&self) -> Option<flatbuffers::Vector<'a, GeometryType>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, GeometryType>>>(LayerInfo::VT_GEOMETRY_TYPES, None)}
  }
  #[inline]
  pub fn min_level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(LayerInfo::VT_MIN_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max_level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(LayerInfo::VT_MAX_LEVEL, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for LayerInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, GeometryType>>>("geometry_types", Self::VT_GEOMETRY_TYPES, false)?
     .visit_field::<u8>("min_level", Self::VT_MIN_LEVEL, false)?
     .visit_field::<u8>("max_level", Self::VT_MAX_LEVEL, false)?
     .finish();
    Ok(())
  }
}
pub struct LayerInfoArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub geometry_types: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, GeometryType>>>,
    pub min_level: u8,
    pub max_level: u8,
}
impl<'a> Default for LayerInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    LayerInfoArgs {
      name: None, // required field
      geometry_types: None,
      min_level: 0,
      max_level: 0,
    }
  }
}

pub struct LayerInfoBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LayerInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LayerInfo::VT_NAME, name);
  }
  #[inline]
  pub fn add_geometry_types(&mut self, geometry_types: flatbuffers::WIPOffset<flatbuffers::Vector<'b , GeometryType>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LayerInfo::VT_GEOMETRY_TYPES, geometry_types);
  }
  #[inline]
  pub fn add_min_level(&mut self, min_level: u8) {
    self.fbb_.push_slot::<u8>(LayerInfo::VT_MIN_LEVEL, min_level, 0);
  }
  #[inline]
  pub fn add_max_level(&mut self, max_level: u8) {
    self.fbb_.push_slot::<u8>(LayerInfo::VT_MAX_LEVEL, max_level, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LayerInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LayerInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LayerInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LayerInfo::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LayerInfo<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LayerInfo");
      ds.field("name", &self.name());
      ds.field("geometry_types", &self.geometry_types());
      ds.field("min_level", &self.min_level());
      ds.field("max_level", &self.max_level());
      ds.finish()
  }
}
pub enum TilesetOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Tileset<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Tileset<'a> {
  type Inner = Tileset<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Tileset<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_NAME: flatbuffers::VOffsetT = 6;
  pub const VT_BOUNDS: flatbuffers::VOffsetT = 8;
  pub const VT_ELEVATION_RANGE: flatbuffers::VOffsetT = 10;
  pub const VT_MIN_LEVEL: flatbuffers::VOffsetT = 12;
  pub const VT_MAX_LEVEL: flatbuffers::VOffsetT = 14;
  pub const VT_ROOT_ERROR: flatbuffers::VOffsetT = 16;
  pub const VT_LAYERS: flatbuffers::VOffsetT = 18;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Tileset { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TilesetArgs<'args>
  ) -> flatbuffers::WIPOffset<Tileset<'bldr>> {
    let mut builder = TilesetBuilder::new(_fbb);
    builder.add_root_error(args.root_error);
    if let Some(x) = args.layers { builder.add_layers(x); }
    if let Some(x) = args.elevation_range { builder.add_elevation_range(x); }
    if let Some(x) = args.bounds { builder.add_bounds(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_version(args.version);
    builder.add_max_level(args.max_level);
    builder.add_min_level(args.min_level);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Tileset::VT_VERSION, Some(1)).unwrap()}
  }
  #[inline]
  pub fn name(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Tileset::VT_NAME, None)}
  }
  #[inline]
  pub fn bounds(&self) -> Option<&'a Bounds> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Bounds>(Tileset::VT_BOUNDS, None)}
  }
  #[inline]
  pub fn elevation_range(&self) -> Option<&'a ElevationRange> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ElevationRange>(Tileset::VT_ELEVATION_RANGE, None)}
  }
  #[inline]
  pub fn min_level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Tileset::VT_MIN_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn max_level(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Tileset::VT_MAX_LEVEL, Some(0)).unwrap()}
  }
  #[inline]
  pub fn root_error(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Tileset::VT_ROOT_ERROR, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn layers(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LayerInfo<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LayerInfo>>>>(Tileset::VT_LAYERS, None)}
  }
}

impl flatbuffers::Verifiable for Tileset<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u16>("version", Self::VT_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, false)?
     .visit_field::<Bounds>("bounds", Self::VT_BOUNDS, false)?
     .visit_field::<ElevationRange>("elevation_range", Self::VT_ELEVATION_RANGE, false)?
     .visit_field::<u8>("min_level", Self::VT_MIN_LEVEL, false)?
     .visit_field::<u8>("max_level", Self::VT_MAX_LEVEL, false)?
     .visit_field::<f64>("root_error", Self::VT_ROOT_ERROR, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<LayerInfo>>>>("layers", Self::VT_LAYERS, false)?
     .finish();
    Ok(())
  }
}
pub struct TilesetArgs<'a> {
    pub version: u16,
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub bounds: Option<&'a Bounds>,
    pub elevation_range: Option<&'a ElevationRange>,
    pub min_level: u8,
    pub max_level: u8,
    pub root_error: f64,
    pub layers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<LayerInfo<'a>>>>>,
}
impl<'a> Default for TilesetArgs<'a> {
  #[inline]
  fn default() -> Self {
    TilesetArgs {
      version: 1,
      name: None,
      bounds: None,
      elevation_range: None,
      min_level: 0,
      max_level: 0,
      root_error: 0.0,
      layers: None,
    }
  }
}

pub struct TilesetBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TilesetBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u16) {
    self.fbb_.push_slot::<u16>(Tileset::VT_VERSION, version, 1);
  }
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tileset::VT_NAME, name);
  }
  #[inline]
  pub fn add_bounds(&mut self, bounds: &Bounds) {
    self.fbb_.push_slot_always::<&Bounds>(Tileset::VT_BOUNDS, bounds);
  }
  #[inline]
  pub fn add_elevation_range(&mut self, elevation_range: &ElevationRange) {
    self.fbb_.push_slot_always::<&ElevationRange>(Tileset::VT_ELEVATION_RANGE, elevation_range);
  }
  #[inline]
  pub fn add_min_level(&mut self, min_level: u8) {
    self.fbb_.push_slot::<u8>(Tileset::VT_MIN_LEVEL, min_level, 0);
  }
  #[inline]
  pub fn add_max_level(&mut self, max_level: u8) {
    self.fbb_.push_slot::<u8>(Tileset::VT_MAX_LEVEL, max_level, 0);
  }
  #[inline]
  pub fn add_root_error(&mut self, root_error: f64) {
    self.fbb_.push_slot::<f64>(Tileset::VT_ROOT_ERROR, root_error, 0.0);
  }
  #[inline]
  pub fn add_layers(&mut self, layers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<LayerInfo<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tileset::VT_LAYERS, layers);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TilesetBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TilesetBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Tileset<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Tileset<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Tileset");
      ds.field("version", &self.version());
      ds.field("name", &self.name());
      ds.field("bounds", &self.bounds());
      ds.field("elevation_range", &self.elevation_range());
      ds.field("min_level", &self.min_level());
      ds.field("max_level", &self.max_level());
      ds.field("root_error", &self.root_error());
      ds.field("layers", &self.layers());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Tileset`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tileset_unchecked`.
pub fn root_as_tileset(buf: &[u8]) -> Result<Tileset, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Tileset>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Tileset` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_tileset_unchecked`.
pub fn size_prefixed_root_as_tileset(buf: &[u8]) -> Result<Tileset, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Tileset>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Tileset` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tileset_unchecked`.
pub fn root_as_tileset_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Tileset<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Tileset<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Tileset` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tileset_unchecked`.
pub fn size_prefixed_root_as_tileset_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Tileset<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Tileset<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Tileset and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Tileset`.
pub unsafe fn root_as_tileset_unchecked(buf: &[u8]) -> Tileset {
  flatbuffers::root_unchecked::<Tileset>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Tileset and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Tileset`.
pub unsafe fn size_prefixed_root_as_tileset_unchecked(buf: &[u8]) -> Tileset {
  flatbuffers::size_prefixed_root_unchecked::<Tileset>(buf)
}
pub const TILESET_IDENTIFIER: &str = "arpi";

#[inline]
pub fn tileset_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, TILESET_IDENTIFIER, false)
}

#[inline]
pub fn tileset_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, TILESET_IDENTIFIER, true)
}

pub const TILESET_EXTENSION: &str = "arpi";

#[inline]
pub fn finish_tileset_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Tileset<'a>>) {
  fbb.finish(root, Some(TILESET_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_tileset_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Tileset<'a>>) {
  fbb.finish_size_prefixed(root, Some(TILESET_IDENTIFIER));
}
}  // pub mod tiles
}  // pub mod arpentry

