// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod arpentry {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod tiles {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_PROPERTY_VALUE_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_PROPERTY_VALUE_TYPE: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_PROPERTY_VALUE_TYPE: [PropertyValueType; 4] = [
  PropertyValueType::String,
  PropertyValueType::Int,
  PropertyValueType::Double,
  PropertyValueType::Bool,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct PropertyValueType(pub u8);
#[allow(non_upper_case_globals)]
impl PropertyValueType {
  pub const String: Self = Self(0);
  pub const Int: Self = Self(1);
  pub const Double: Self = Self(2);
  pub const Bool: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::String,
    Self::Int,
    Self::Double,
    Self::Bool,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::String => Some("String"),
      Self::Int => Some("Int"),
      Self::Double => Some("Double"),
      Self::Bool => Some("Bool"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for PropertyValueType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for PropertyValueType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for PropertyValueType {
    type Output = PropertyValueType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for PropertyValueType {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for PropertyValueType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for PropertyValueType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_GEOMETRY: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_GEOMETRY: u8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_GEOMETRY: [Geometry; 5] = [
  Geometry::NONE,
  Geometry::PointGeometry,
  Geometry::LineGeometry,
  Geometry::PolygonGeometry,
  Geometry::MeshGeometry,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Geometry(pub u8);
#[allow(non_upper_case_globals)]
impl Geometry {
  pub const NONE: Self = Self(0);
  pub const PointGeometry: Self = Self(1);
  pub const LineGeometry: Self = Self(2);
  pub const PolygonGeometry: Self = Self(3);
  pub const MeshGeometry: Self = Self(4);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::PointGeometry,
    Self::LineGeometry,
    Self::PolygonGeometry,
    Self::MeshGeometry,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::PointGeometry => Some("PointGeometry"),
      Self::LineGeometry => Some("LineGeometry"),
      Self::PolygonGeometry => Some("PolygonGeometry"),
      Self::MeshGeometry => Some("MeshGeometry"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Geometry {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Geometry {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for Geometry {
    type Output = Geometry;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for Geometry {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Geometry {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Geometry {}
pub struct GeometryUnionTableOffset {}

// struct Color, aligned to 1
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Color(pub [u8; 4]);
impl Default for Color { 
  fn default() -> Self { 
    Self([0; 4])
  }
}
impl core::fmt::Debug for Color {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Color")
      .field("r", &self.r())
      .field("g", &self.g())
      .field("b", &self.b())
      .field("a", &self.a())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Color {}
impl<'a> flatbuffers::Follow<'a> for Color {
  type Inner = &'a Color;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Color>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Color {
  type Inner = &'a Color;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Color>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Color {
    type Output = Color;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Color as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
}

impl<'a> flatbuffers::Verifiable for Color {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Color {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    r: u8,
    g: u8,
    b: u8,
    a: u8,
  ) -> Self {
    let mut s = Self([0; 4]);
    s.set_r(r);
    s.set_g(g);
    s.set_b(b);
    s.set_a(a);
    s
  }

  pub fn r(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_r(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn g(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[1..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_g(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[1..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn b(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[2..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_b(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[2..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn a(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[3..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_a(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[3..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct Part, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Part(pub [u8; 16]);
impl Default for Part { 
  fn default() -> Self { 
    Self([0; 16])
  }
}
impl core::fmt::Debug for Part {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Part")
      .field("first_index", &self.first_index())
      .field("index_count", &self.index_count())
      .field("color", &self.color())
      .field("roughness", &self.roughness())
      .field("metalness", &self.metalness())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Part {}
impl<'a> flatbuffers::Follow<'a> for Part {
  type Inner = &'a Part;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Part>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Part {
  type Inner = &'a Part;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Part>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Part {
    type Output = Part;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Part as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
    // Patched (flatc 24.3.25 omits this): align this struct to 4 in the builder so
    // flatcc's verifier accepts the buffer; struct stays `repr(transparent)`.
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> flatbuffers::Verifiable for Part {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Part {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    first_index: u32,
    index_count: u32,
    color: &Color,
    roughness: u8,
    metalness: u8,
  ) -> Self {
    let mut s = Self([0; 16]);
    s.set_first_index(first_index);
    s.set_index_count(index_count);
    s.set_color(color);
    s.set_roughness(roughness);
    s.set_metalness(metalness);
    s
  }

  pub fn first_index(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_first_index(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn index_count(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_index_count(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn color(&self) -> &Color {
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid struct in this slot
    unsafe { &*(self.0[8..].as_ptr() as *const Color) }
  }

  #[allow(clippy::identity_op)]
  pub fn set_color(&mut self, x: &Color) {
    self.0[8..8 + 4].copy_from_slice(&x.0)
  }

  pub fn roughness(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[12..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_roughness(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[12..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn metalness(&self) -> u8 {
    let mut mem = core::mem::MaybeUninit::<<u8 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[13..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_metalness(&mut self, x: u8) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[13..].as_mut_ptr(),
        core::mem::size_of::<<u8 as EndianScalar>::Scalar>(),
      );
    }
  }

}

// struct Property, aligned to 4
#[repr(transparent)]
#[derive(Clone, Copy, PartialEq)]
pub struct Property(pub [u8; 8]);
impl Default for Property { 
  fn default() -> Self { 
    Self([0; 8])
  }
}
impl core::fmt::Debug for Property {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    f.debug_struct("Property")
      .field("key", &self.key())
      .field("value", &self.value())
      .finish()
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Property {}
impl<'a> flatbuffers::Follow<'a> for Property {
  type Inner = &'a Property;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    <&'a Property>::follow(buf, loc)
  }
}
impl<'a> flatbuffers::Follow<'a> for &'a Property {
  type Inner = &'a Property;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    flatbuffers::follow_cast_ref::<Property>(buf, loc)
  }
}
impl<'b> flatbuffers::Push for Property {
    type Output = Property;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        let src = ::core::slice::from_raw_parts(self as *const Property as *const u8, Self::size());
        dst.copy_from_slice(src);
    }
    // Patched (flatc 24.3.25 omits this): align this struct to 4 in the builder so
    // flatcc's verifier accepts the buffer; struct stays `repr(transparent)`.
    #[inline]
    fn alignment() -> flatbuffers::PushAlignment {
        flatbuffers::PushAlignment::new(4)
    }
}

impl<'a> flatbuffers::Verifiable for Property {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.in_buffer::<Self>(pos)
  }
}

impl<'a> Property {
  #[allow(clippy::too_many_arguments)]
  pub fn new(
    key: u32,
    value: u32,
  ) -> Self {
    let mut s = Self([0; 8]);
    s.set_key(key);
    s.set_value(value);
    s
  }

  pub fn key(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[0..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_key(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[0..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

  pub fn value(&self) -> u32 {
    let mut mem = core::mem::MaybeUninit::<<u32 as EndianScalar>::Scalar>::uninit();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    EndianScalar::from_little_endian(unsafe {
      core::ptr::copy_nonoverlapping(
        self.0[4..].as_ptr(),
        mem.as_mut_ptr() as *mut u8,
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
      mem.assume_init()
    })
  }

  pub fn set_value(&mut self, x: u32) {
    let x_le = x.to_little_endian();
    // Safety:
    // Created from a valid Table for this object
    // Which contains a valid value in this slot
    unsafe {
      core::ptr::copy_nonoverlapping(
        &x_le as *const _ as *const u8,
        self.0[4..].as_mut_ptr(),
        core::mem::size_of::<<u32 as EndianScalar>::Scalar>(),
      );
    }
  }

}

pub enum PointGeometryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PointGeometry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PointGeometry<'a> {
  type Inner = PointGeometry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PointGeometry<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_Z: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PointGeometry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PointGeometryArgs<'args>
  ) -> flatbuffers::WIPOffset<PointGeometry<'bldr>> {
    let mut builder = PointGeometryBuilder::new(_fbb);
    if let Some(x) = args.z { builder.add_z(x); }
    if let Some(x) = args.y { builder.add_y(x); }
    if let Some(x) = args.x { builder.add_x(x); }
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(PointGeometry::VT_X, None).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(PointGeometry::VT_Y, None).unwrap()}
  }
  #[inline]
  pub fn z(&self) -> Option<flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(PointGeometry::VT_Z, None)}
  }
}

impl flatbuffers::Verifiable for PointGeometry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("x", Self::VT_X, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("y", Self::VT_Y, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("z", Self::VT_Z, false)?
     .finish();
    Ok(())
  }
}
pub struct PointGeometryArgs<'a> {
    pub x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
}
impl<'a> Default for PointGeometryArgs<'a> {
  #[inline]
  fn default() -> Self {
    PointGeometryArgs {
      x: None, // required field
      y: None, // required field
      z: None,
    }
  }
}

pub struct PointGeometryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PointGeometryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_x(&mut self, x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PointGeometry::VT_X, x);
  }
  #[inline]
  pub fn add_y(&mut self, y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PointGeometry::VT_Y, y);
  }
  #[inline]
  pub fn add_z(&mut self, z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PointGeometry::VT_Z, z);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PointGeometryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PointGeometryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PointGeometry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PointGeometry::VT_X,"x");
    self.fbb_.required(o, PointGeometry::VT_Y,"y");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PointGeometry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PointGeometry");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.finish()
  }
}
pub enum LineGeometryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct LineGeometry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for LineGeometry<'a> {
  type Inner = LineGeometry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> LineGeometry<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_Z: flatbuffers::VOffsetT = 8;
  pub const VT_LINE_OFFSETS: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    LineGeometry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LineGeometryArgs<'args>
  ) -> flatbuffers::WIPOffset<LineGeometry<'bldr>> {
    let mut builder = LineGeometryBuilder::new(_fbb);
    if let Some(x) = args.line_offsets { builder.add_line_offsets(x); }
    if let Some(x) = args.z { builder.add_z(x); }
    if let Some(x) = args.y { builder.add_y(x); }
    if let Some(x) = args.x { builder.add_x(x); }
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(LineGeometry::VT_X, None).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(LineGeometry::VT_Y, None).unwrap()}
  }
  #[inline]
  pub fn z(&self) -> Option<flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(LineGeometry::VT_Z, None)}
  }
  #[inline]
  pub fn line_offsets(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(LineGeometry::VT_LINE_OFFSETS, None)}
  }
}

impl flatbuffers::Verifiable for LineGeometry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("x", Self::VT_X, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("y", Self::VT_Y, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("z", Self::VT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("line_offsets", Self::VT_LINE_OFFSETS, false)?
     .finish();
    Ok(())
  }
}
pub struct LineGeometryArgs<'a> {
    pub x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
    pub line_offsets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for LineGeometryArgs<'a> {
  #[inline]
  fn default() -> Self {
    LineGeometryArgs {
      x: None, // required field
      y: None, // required field
      z: None,
      line_offsets: None,
    }
  }
}

pub struct LineGeometryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LineGeometryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_x(&mut self, x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LineGeometry::VT_X, x);
  }
  #[inline]
  pub fn add_y(&mut self, y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LineGeometry::VT_Y, y);
  }
  #[inline]
  pub fn add_z(&mut self, z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LineGeometry::VT_Z, z);
  }
  #[inline]
  pub fn add_line_offsets(&mut self, line_offsets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(LineGeometry::VT_LINE_OFFSETS, line_offsets);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LineGeometryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LineGeometryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<LineGeometry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, LineGeometry::VT_X,"x");
    self.fbb_.required(o, LineGeometry::VT_Y,"y");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for LineGeometry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("LineGeometry");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.field("line_offsets", &self.line_offsets());
      ds.finish()
  }
}
pub enum PolygonGeometryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PolygonGeometry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for PolygonGeometry<'a> {
  type Inner = PolygonGeometry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> PolygonGeometry<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_Z: flatbuffers::VOffsetT = 8;
  pub const VT_RING_OFFSETS: flatbuffers::VOffsetT = 10;
  pub const VT_POLYGON_OFFSETS: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    PolygonGeometry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PolygonGeometryArgs<'args>
  ) -> flatbuffers::WIPOffset<PolygonGeometry<'bldr>> {
    let mut builder = PolygonGeometryBuilder::new(_fbb);
    if let Some(x) = args.polygon_offsets { builder.add_polygon_offsets(x); }
    if let Some(x) = args.ring_offsets { builder.add_ring_offsets(x); }
    if let Some(x) = args.z { builder.add_z(x); }
    if let Some(x) = args.y { builder.add_y(x); }
    if let Some(x) = args.x { builder.add_x(x); }
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(PolygonGeometry::VT_X, None).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(PolygonGeometry::VT_Y, None).unwrap()}
  }
  #[inline]
  pub fn z(&self) -> Option<flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(PolygonGeometry::VT_Z, None)}
  }
  #[inline]
  pub fn ring_offsets(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(PolygonGeometry::VT_RING_OFFSETS, None)}
  }
  #[inline]
  pub fn polygon_offsets(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(PolygonGeometry::VT_POLYGON_OFFSETS, None)}
  }
}

impl flatbuffers::Verifiable for PolygonGeometry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("x", Self::VT_X, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("y", Self::VT_Y, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("z", Self::VT_Z, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("ring_offsets", Self::VT_RING_OFFSETS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("polygon_offsets", Self::VT_POLYGON_OFFSETS, false)?
     .finish();
    Ok(())
  }
}
pub struct PolygonGeometryArgs<'a> {
    pub x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
    pub ring_offsets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub polygon_offsets: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for PolygonGeometryArgs<'a> {
  #[inline]
  fn default() -> Self {
    PolygonGeometryArgs {
      x: None, // required field
      y: None, // required field
      z: None,
      ring_offsets: None,
      polygon_offsets: None,
    }
  }
}

pub struct PolygonGeometryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> PolygonGeometryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_x(&mut self, x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PolygonGeometry::VT_X, x);
  }
  #[inline]
  pub fn add_y(&mut self, y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PolygonGeometry::VT_Y, y);
  }
  #[inline]
  pub fn add_z(&mut self, z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PolygonGeometry::VT_Z, z);
  }
  #[inline]
  pub fn add_ring_offsets(&mut self, ring_offsets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PolygonGeometry::VT_RING_OFFSETS, ring_offsets);
  }
  #[inline]
  pub fn add_polygon_offsets(&mut self, polygon_offsets: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(PolygonGeometry::VT_POLYGON_OFFSETS, polygon_offsets);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> PolygonGeometryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PolygonGeometryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<PolygonGeometry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, PolygonGeometry::VT_X,"x");
    self.fbb_.required(o, PolygonGeometry::VT_Y,"y");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for PolygonGeometry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("PolygonGeometry");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.field("ring_offsets", &self.ring_offsets());
      ds.field("polygon_offsets", &self.polygon_offsets());
      ds.finish()
  }
}
pub enum MeshGeometryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MeshGeometry<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MeshGeometry<'a> {
  type Inner = MeshGeometry<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> MeshGeometry<'a> {
  pub const VT_X: flatbuffers::VOffsetT = 4;
  pub const VT_Y: flatbuffers::VOffsetT = 6;
  pub const VT_Z: flatbuffers::VOffsetT = 8;
  pub const VT_INDICES: flatbuffers::VOffsetT = 10;
  pub const VT_NORMALS: flatbuffers::VOffsetT = 12;
  pub const VT_PARTS: flatbuffers::VOffsetT = 14;
  pub const VT_EDGE_WEST: flatbuffers::VOffsetT = 16;
  pub const VT_EDGE_SOUTH: flatbuffers::VOffsetT = 18;
  pub const VT_EDGE_EAST: flatbuffers::VOffsetT = 20;
  pub const VT_EDGE_NORTH: flatbuffers::VOffsetT = 22;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MeshGeometry { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MeshGeometryArgs<'args>
  ) -> flatbuffers::WIPOffset<MeshGeometry<'bldr>> {
    let mut builder = MeshGeometryBuilder::new(_fbb);
    if let Some(x) = args.edge_north { builder.add_edge_north(x); }
    if let Some(x) = args.edge_east { builder.add_edge_east(x); }
    if let Some(x) = args.edge_south { builder.add_edge_south(x); }
    if let Some(x) = args.edge_west { builder.add_edge_west(x); }
    if let Some(x) = args.parts { builder.add_parts(x); }
    if let Some(x) = args.normals { builder.add_normals(x); }
    if let Some(x) = args.indices { builder.add_indices(x); }
    if let Some(x) = args.z { builder.add_z(x); }
    if let Some(x) = args.y { builder.add_y(x); }
    if let Some(x) = args.x { builder.add_x(x); }
    builder.finish()
  }


  #[inline]
  pub fn x(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(MeshGeometry::VT_X, None).unwrap()}
  }
  #[inline]
  pub fn y(&self) -> flatbuffers::Vector<'a, u16> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u16>>>(MeshGeometry::VT_Y, None).unwrap()}
  }
  #[inline]
  pub fn z(&self) -> flatbuffers::Vector<'a, i32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(MeshGeometry::VT_Z, None).unwrap()}
  }
  #[inline]
  pub fn indices(&self) -> flatbuffers::Vector<'a, u32> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(MeshGeometry::VT_INDICES, None).unwrap()}
  }
  #[inline]
  pub fn normals(&self) -> Option<flatbuffers::Vector<'a, i8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i8>>>(MeshGeometry::VT_NORMALS, None)}
  }
  #[inline]
  pub fn parts(&self) -> Option<flatbuffers::Vector<'a, Part>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Part>>>(MeshGeometry::VT_PARTS, None)}
  }
  #[inline]
  pub fn edge_west(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(MeshGeometry::VT_EDGE_WEST, None)}
  }
  #[inline]
  pub fn edge_south(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(MeshGeometry::VT_EDGE_SOUTH, None)}
  }
  #[inline]
  pub fn edge_east(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(MeshGeometry::VT_EDGE_EAST, None)}
  }
  #[inline]
  pub fn edge_north(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(MeshGeometry::VT_EDGE_NORTH, None)}
  }
}

impl flatbuffers::Verifiable for MeshGeometry<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("x", Self::VT_X, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u16>>>("y", Self::VT_Y, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("z", Self::VT_Z, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("indices", Self::VT_INDICES, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i8>>>("normals", Self::VT_NORMALS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Part>>>("parts", Self::VT_PARTS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("edge_west", Self::VT_EDGE_WEST, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("edge_south", Self::VT_EDGE_SOUTH, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("edge_east", Self::VT_EDGE_EAST, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("edge_north", Self::VT_EDGE_NORTH, false)?
     .finish();
    Ok(())
  }
}
pub struct MeshGeometryArgs<'a> {
    pub x: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub y: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u16>>>,
    pub z: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
    pub indices: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub normals: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i8>>>,
    pub parts: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Part>>>,
    pub edge_west: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub edge_south: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub edge_east: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub edge_north: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for MeshGeometryArgs<'a> {
  #[inline]
  fn default() -> Self {
    MeshGeometryArgs {
      x: None, // required field
      y: None, // required field
      z: None, // required field
      indices: None, // required field
      normals: None,
      parts: None,
      edge_west: None,
      edge_south: None,
      edge_east: None,
      edge_north: None,
    }
  }
}

pub struct MeshGeometryBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MeshGeometryBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_x(&mut self, x: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_X, x);
  }
  #[inline]
  pub fn add_y(&mut self, y: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u16>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_Y, y);
  }
  #[inline]
  pub fn add_z(&mut self, z: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_Z, z);
  }
  #[inline]
  pub fn add_indices(&mut self, indices: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_INDICES, indices);
  }
  #[inline]
  pub fn add_normals(&mut self, normals: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_NORMALS, normals);
  }
  #[inline]
  pub fn add_parts(&mut self, parts: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Part>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_PARTS, parts);
  }
  #[inline]
  pub fn add_edge_west(&mut self, edge_west: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_EDGE_WEST, edge_west);
  }
  #[inline]
  pub fn add_edge_south(&mut self, edge_south: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_EDGE_SOUTH, edge_south);
  }
  #[inline]
  pub fn add_edge_east(&mut self, edge_east: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_EDGE_EAST, edge_east);
  }
  #[inline]
  pub fn add_edge_north(&mut self, edge_north: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MeshGeometry::VT_EDGE_NORTH, edge_north);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MeshGeometryBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MeshGeometryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MeshGeometry<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, MeshGeometry::VT_X,"x");
    self.fbb_.required(o, MeshGeometry::VT_Y,"y");
    self.fbb_.required(o, MeshGeometry::VT_Z,"z");
    self.fbb_.required(o, MeshGeometry::VT_INDICES,"indices");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MeshGeometry<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MeshGeometry");
      ds.field("x", &self.x());
      ds.field("y", &self.y());
      ds.field("z", &self.z());
      ds.field("indices", &self.indices());
      ds.field("normals", &self.normals());
      ds.field("parts", &self.parts());
      ds.field("edge_west", &self.edge_west());
      ds.field("edge_south", &self.edge_south());
      ds.field("edge_east", &self.edge_east());
      ds.field("edge_north", &self.edge_north());
      ds.finish()
  }
}
pub enum ValueOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Value<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Value<'a> {
  type Inner = Value<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Value<'a> {
  pub const VT_TYPE_: flatbuffers::VOffsetT = 4;
  pub const VT_STRING_VALUE: flatbuffers::VOffsetT = 6;
  pub const VT_INT_VALUE: flatbuffers::VOffsetT = 8;
  pub const VT_DOUBLE_VALUE: flatbuffers::VOffsetT = 10;
  pub const VT_BOOL_VALUE: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Value { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ValueArgs<'args>
  ) -> flatbuffers::WIPOffset<Value<'bldr>> {
    let mut builder = ValueBuilder::new(_fbb);
    builder.add_double_value(args.double_value);
    builder.add_int_value(args.int_value);
    if let Some(x) = args.string_value { builder.add_string_value(x); }
    builder.add_bool_value(args.bool_value);
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn type_(&self) -> PropertyValueType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<PropertyValueType>(Value::VT_TYPE_, Some(PropertyValueType::String)).unwrap()}
  }
  #[inline]
  pub fn string_value(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Value::VT_STRING_VALUE, None)}
  }
  #[inline]
  pub fn int_value(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(Value::VT_INT_VALUE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn double_value(&self) -> f64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f64>(Value::VT_DOUBLE_VALUE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn bool_value(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Value::VT_BOOL_VALUE, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for Value<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<PropertyValueType>("type_", Self::VT_TYPE_, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("string_value", Self::VT_STRING_VALUE, false)?
     .visit_field::<i64>("int_value", Self::VT_INT_VALUE, false)?
     .visit_field::<f64>("double_value", Self::VT_DOUBLE_VALUE, false)?
     .visit_field::<bool>("bool_value", Self::VT_BOOL_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct ValueArgs<'a> {
    pub type_: PropertyValueType,
    pub string_value: Option<flatbuffers::WIPOffset<&'a str>>,
    pub int_value: i64,
    pub double_value: f64,
    pub bool_value: bool,
}
impl<'a> Default for ValueArgs<'a> {
  #[inline]
  fn default() -> Self {
    ValueArgs {
      type_: PropertyValueType::String,
      string_value: None,
      int_value: 0,
      double_value: 0.0,
      bool_value: false,
    }
  }
}

pub struct ValueBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ValueBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_type_(&mut self, type_: PropertyValueType) {
    self.fbb_.push_slot::<PropertyValueType>(Value::VT_TYPE_, type_, PropertyValueType::String);
  }
  #[inline]
  pub fn add_string_value(&mut self, string_value: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Value::VT_STRING_VALUE, string_value);
  }
  #[inline]
  pub fn add_int_value(&mut self, int_value: i64) {
    self.fbb_.push_slot::<i64>(Value::VT_INT_VALUE, int_value, 0);
  }
  #[inline]
  pub fn add_double_value(&mut self, double_value: f64) {
    self.fbb_.push_slot::<f64>(Value::VT_DOUBLE_VALUE, double_value, 0.0);
  }
  #[inline]
  pub fn add_bool_value(&mut self, bool_value: bool) {
    self.fbb_.push_slot::<bool>(Value::VT_BOOL_VALUE, bool_value, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ValueBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ValueBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Value<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Value<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Value");
      ds.field("type_", &self.type_());
      ds.field("string_value", &self.string_value());
      ds.field("int_value", &self.int_value());
      ds.field("double_value", &self.double_value());
      ds.field("bool_value", &self.bool_value());
      ds.finish()
  }
}
pub enum FeatureOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Feature<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Feature<'a> {
  type Inner = Feature<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Feature<'a> {
  pub const VT_ID: flatbuffers::VOffsetT = 4;
  pub const VT_GEOMETRY_TYPE: flatbuffers::VOffsetT = 6;
  pub const VT_GEOMETRY: flatbuffers::VOffsetT = 8;
  pub const VT_PROPERTIES: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Feature { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FeatureArgs<'args>
  ) -> flatbuffers::WIPOffset<Feature<'bldr>> {
    let mut builder = FeatureBuilder::new(_fbb);
    builder.add_id(args.id);
    if let Some(x) = args.properties { builder.add_properties(x); }
    if let Some(x) = args.geometry { builder.add_geometry(x); }
    builder.add_geometry_type(args.geometry_type);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Feature::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn geometry_type(&self) -> Geometry {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Geometry>(Feature::VT_GEOMETRY_TYPE, Some(Geometry::NONE)).unwrap()}
  }
  #[inline]
  pub fn geometry(&self) -> flatbuffers::Table<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(Feature::VT_GEOMETRY, None).unwrap()}
  }
  #[inline]
  pub fn properties(&self) -> Option<flatbuffers::Vector<'a, Property>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, Property>>>(Feature::VT_PROPERTIES, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn geometry_as_point_geometry(&self) -> Option<PointGeometry<'a>> {
    if self.geometry_type() == Geometry::PointGeometry {
      let u = self.geometry();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { PointGeometry::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn geometry_as_line_geometry(&self) -> Option<LineGeometry<'a>> {
    if self.geometry_type() == Geometry::LineGeometry {
      let u = self.geometry();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { LineGeometry::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn geometry_as_polygon_geometry(&self) -> Option<PolygonGeometry<'a>> {
    if self.geometry_type() == Geometry::PolygonGeometry {
      let u = self.geometry();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { PolygonGeometry::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn geometry_as_mesh_geometry(&self) -> Option<MeshGeometry<'a>> {
    if self.geometry_type() == Geometry::MeshGeometry {
      let u = self.geometry();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { MeshGeometry::init_from_table(u) })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for Feature<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_union::<Geometry, _>("geometry_type", Self::VT_GEOMETRY_TYPE, "geometry", Self::VT_GEOMETRY, true, |key, v, pos| {
        match key {
          Geometry::PointGeometry => v.verify_union_variant::<flatbuffers::ForwardsUOffset<PointGeometry>>("Geometry::PointGeometry", pos),
          Geometry::LineGeometry => v.verify_union_variant::<flatbuffers::ForwardsUOffset<LineGeometry>>("Geometry::LineGeometry", pos),
          Geometry::PolygonGeometry => v.verify_union_variant::<flatbuffers::ForwardsUOffset<PolygonGeometry>>("Geometry::PolygonGeometry", pos),
          Geometry::MeshGeometry => v.verify_union_variant::<flatbuffers::ForwardsUOffset<MeshGeometry>>("Geometry::MeshGeometry", pos),
          _ => Ok(()),
        }
     })?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, Property>>>("properties", Self::VT_PROPERTIES, false)?
     .finish();
    Ok(())
  }
}
pub struct FeatureArgs<'a> {
    pub id: u64,
    pub geometry_type: Geometry,
    pub geometry: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
    pub properties: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, Property>>>,
}
impl<'a> Default for FeatureArgs<'a> {
  #[inline]
  fn default() -> Self {
    FeatureArgs {
      id: 0,
      geometry_type: Geometry::NONE,
      geometry: None, // required field
      properties: None,
    }
  }
}

pub struct FeatureBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> FeatureBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(Feature::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_geometry_type(&mut self, geometry_type: Geometry) {
    self.fbb_.push_slot::<Geometry>(Feature::VT_GEOMETRY_TYPE, geometry_type, Geometry::NONE);
  }
  #[inline]
  pub fn add_geometry(&mut self, geometry: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Feature::VT_GEOMETRY, geometry);
  }
  #[inline]
  pub fn add_properties(&mut self, properties: flatbuffers::WIPOffset<flatbuffers::Vector<'b , Property>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Feature::VT_PROPERTIES, properties);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> FeatureBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FeatureBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Feature<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Feature::VT_GEOMETRY,"geometry");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Feature<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Feature");
      ds.field("id", &self.id());
      ds.field("geometry_type", &self.geometry_type());
      match self.geometry_type() {
        Geometry::PointGeometry => {
          if let Some(x) = self.geometry_as_point_geometry() {
            ds.field("geometry", &x)
          } else {
            ds.field("geometry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Geometry::LineGeometry => {
          if let Some(x) = self.geometry_as_line_geometry() {
            ds.field("geometry", &x)
          } else {
            ds.field("geometry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Geometry::PolygonGeometry => {
          if let Some(x) = self.geometry_as_polygon_geometry() {
            ds.field("geometry", &x)
          } else {
            ds.field("geometry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        Geometry::MeshGeometry => {
          if let Some(x) = self.geometry_as_mesh_geometry() {
            ds.field("geometry", &x)
          } else {
            ds.field("geometry", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("geometry", &x)
        },
      };
      ds.field("properties", &self.properties());
      ds.finish()
  }
}
pub enum LayerOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Layer<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Layer<'a> {
  type Inner = Layer<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Layer<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_FEATURES: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Layer { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args LayerArgs<'args>
  ) -> flatbuffers::WIPOffset<Layer<'bldr>> {
    let mut builder = LayerBuilder::new(_fbb);
    if let Some(x) = args.features { builder.add_features(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Layer::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn features(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Feature<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Feature>>>>(Layer::VT_FEATURES, None)}
  }
}

impl flatbuffers::Verifiable for Layer<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Feature>>>>("features", Self::VT_FEATURES, false)?
     .finish();
    Ok(())
  }
}
pub struct LayerArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub features: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Feature<'a>>>>>,
}
impl<'a> Default for LayerArgs<'a> {
  #[inline]
  fn default() -> Self {
    LayerArgs {
      name: None, // required field
      features: None,
    }
  }
}

pub struct LayerBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> LayerBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Layer::VT_NAME, name);
  }
  #[inline]
  pub fn add_features(&mut self, features: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Feature<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Layer::VT_FEATURES, features);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> LayerBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    LayerBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Layer<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Layer::VT_NAME,"name");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Layer<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Layer");
      ds.field("name", &self.name());
      ds.field("features", &self.features());
      ds.finish()
  }
}
pub enum RasterOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Raster<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Raster<'a> {
  type Inner = Raster<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Raster<'a> {
  pub const VT_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_WIDTH: flatbuffers::VOffsetT = 6;
  pub const VT_HEIGHT: flatbuffers::VOffsetT = 8;
  pub const VT_BUFFER: flatbuffers::VOffsetT = 10;
  pub const VT_CHANNELS: flatbuffers::VOffsetT = 12;
  pub const VT_DATA: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Raster { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RasterArgs<'args>
  ) -> flatbuffers::WIPOffset<Raster<'bldr>> {
    let mut builder = RasterBuilder::new(_fbb);
    if let Some(x) = args.data { builder.add_data(x); }
    if let Some(x) = args.name { builder.add_name(x); }
    builder.add_height(args.height);
    builder.add_width(args.width);
    builder.add_channels(args.channels);
    builder.add_buffer(args.buffer);
    builder.finish()
  }


  #[inline]
  pub fn name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Raster::VT_NAME, None).unwrap()}
  }
  #[inline]
  pub fn width(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Raster::VT_WIDTH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn height(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Raster::VT_HEIGHT, Some(0)).unwrap()}
  }
  #[inline]
  pub fn buffer(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Raster::VT_BUFFER, Some(0)).unwrap()}
  }
  #[inline]
  pub fn channels(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(Raster::VT_CHANNELS, Some(1)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> flatbuffers::Vector<'a, u8> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(Raster::VT_DATA, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for Raster<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("name", Self::VT_NAME, true)?
     .visit_field::<u16>("width", Self::VT_WIDTH, false)?
     .visit_field::<u16>("height", Self::VT_HEIGHT, false)?
     .visit_field::<u8>("buffer", Self::VT_BUFFER, false)?
     .visit_field::<u8>("channels", Self::VT_CHANNELS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>("data", Self::VT_DATA, true)?
     .finish();
    Ok(())
  }
}
pub struct RasterArgs<'a> {
    pub name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub width: u16,
    pub height: u16,
    pub buffer: u8,
    pub channels: u8,
    pub data: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for RasterArgs<'a> {
  #[inline]
  fn default() -> Self {
    RasterArgs {
      name: None, // required field
      width: 0,
      height: 0,
      buffer: 0,
      channels: 1,
      data: None, // required field
    }
  }
}

pub struct RasterBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> RasterBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_name(&mut self, name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Raster::VT_NAME, name);
  }
  #[inline]
  pub fn add_width(&mut self, width: u16) {
    self.fbb_.push_slot::<u16>(Raster::VT_WIDTH, width, 0);
  }
  #[inline]
  pub fn add_height(&mut self, height: u16) {
    self.fbb_.push_slot::<u16>(Raster::VT_HEIGHT, height, 0);
  }
  #[inline]
  pub fn add_buffer(&mut self, buffer: u8) {
    self.fbb_.push_slot::<u8>(Raster::VT_BUFFER, buffer, 0);
  }
  #[inline]
  pub fn add_channels(&mut self, channels: u8) {
    self.fbb_.push_slot::<u8>(Raster::VT_CHANNELS, channels, 1);
  }
  #[inline]
  pub fn add_data(&mut self, data: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Raster::VT_DATA, data);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> RasterBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RasterBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Raster<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Raster::VT_NAME,"name");
    self.fbb_.required(o, Raster::VT_DATA,"data");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Raster<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Raster");
      ds.field("name", &self.name());
      ds.field("width", &self.width());
      ds.field("height", &self.height());
      ds.field("buffer", &self.buffer());
      ds.field("channels", &self.channels());
      ds.field("data", &self.data());
      ds.finish()
  }
}
pub enum TileOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Tile<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Tile<'a> {
  type Inner = Tile<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Tile<'a> {
  pub const VT_VERSION: flatbuffers::VOffsetT = 4;
  pub const VT_LAYERS: flatbuffers::VOffsetT = 6;
  pub const VT_KEYS: flatbuffers::VOffsetT = 8;
  pub const VT_VALUES: flatbuffers::VOffsetT = 10;
  pub const VT_RASTERS: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Tile { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TileArgs<'args>
  ) -> flatbuffers::WIPOffset<Tile<'bldr>> {
    let mut builder = TileBuilder::new(_fbb);
    if let Some(x) = args.rasters { builder.add_rasters(x); }
    if let Some(x) = args.values { builder.add_values(x); }
    if let Some(x) = args.keys { builder.add_keys(x); }
    if let Some(x) = args.layers { builder.add_layers(x); }
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(Tile::VT_VERSION, Some(1)).unwrap()}
  }
  #[inline]
  pub fn layers(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Layer<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Layer>>>>(Tile::VT_LAYERS, None)}
  }
  #[inline]
  pub fn keys(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(Tile::VT_KEYS, None)}
  }
  #[inline]
  pub fn values(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Value<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Value>>>>(Tile::VT_VALUES, None)}
  }
  #[inline]
  pub fn rasters(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Raster<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Raster>>>>(Tile::VT_RASTERS, None)}
  }
}

impl flatbuffers::Verifiable for Tile<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<u16>("version", Self::VT_VERSION, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Layer>>>>("layers", Self::VT_LAYERS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("keys", Self::VT_KEYS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Value>>>>("values", Self::VT_VALUES, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Raster>>>>("rasters", Self::VT_RASTERS, false)?
     .finish();
    Ok(())
  }
}
pub struct TileArgs<'a> {
    pub version: u16,
    pub layers: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Layer<'a>>>>>,
    pub keys: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub values: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Value<'a>>>>>,
    pub rasters: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Raster<'a>>>>>,
}
impl<'a> Default for TileArgs<'a> {
  #[inline]
  fn default() -> Self {
    TileArgs {
      version: 1,
      layers: None,
      keys: None,
      values: None,
      rasters: None,
    }
  }
}

pub struct TileBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TileBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u16) {
    self.fbb_.push_slot::<u16>(Tile::VT_VERSION, version, 1);
  }
  #[inline]
  pub fn add_layers(&mut self, layers: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Layer<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tile::VT_LAYERS, layers);
  }
  #[inline]
  pub fn add_keys(&mut self, keys: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tile::VT_KEYS, keys);
  }
  #[inline]
  pub fn add_values(&mut self, values: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Value<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tile::VT_VALUES, values);
  }
  #[inline]
  pub fn add_rasters(&mut self, rasters: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Raster<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Tile::VT_RASTERS, rasters);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TileBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TileBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Tile<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Tile<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Tile");
      ds.field("version", &self.version());
      ds.field("layers", &self.layers());
      ds.field("keys", &self.keys());
      ds.field("values", &self.values());
      ds.field("rasters", &self.rasters());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Tile`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tile_unchecked`.
pub fn root_as_tile(buf: &[u8]) -> Result<Tile, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Tile>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Tile` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_tile_unchecked`.
pub fn size_prefixed_root_as_tile(buf: &[u8]) -> Result<Tile, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Tile>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Tile` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tile_unchecked`.
pub fn root_as_tile_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Tile<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Tile<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Tile` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_tile_unchecked`.
pub fn size_prefixed_root_as_tile_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Tile<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Tile<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Tile and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Tile`.
pub unsafe fn root_as_tile_unchecked(buf: &[u8]) -> Tile {
  flatbuffers::root_unchecked::<Tile>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Tile and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Tile`.
pub unsafe fn size_prefixed_root_as_tile_unchecked(buf: &[u8]) -> Tile {
  flatbuffers::size_prefixed_root_unchecked::<Tile>(buf)
}
pub const TILE_IDENTIFIER: &str = "arpt";

#[inline]
pub fn tile_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, TILE_IDENTIFIER, false)
}

#[inline]
pub fn tile_size_prefixed_buffer_has_identifier(buf: &[u8]) -> bool {
  flatbuffers::buffer_has_identifier(buf, TILE_IDENTIFIER, true)
}

pub const TILE_EXTENSION: &str = "arpt";

#[inline]
pub fn finish_tile_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<Tile<'a>>) {
  fbb.finish(root, Some(TILE_IDENTIFIER));
}

#[inline]
pub fn finish_size_prefixed_tile_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<Tile<'a>>) {
  fbb.finish_size_prefixed(root, Some(TILE_IDENTIFIER));
}
}  // pub mod tiles
}  // pub mod arpentry

