//! FlatBuffers bindings generated by `flatc` from `../schemas/*.fbs`, checked in
//! under `src/fb/`. They are read/written with the `flatbuffers` runtime and are
//! byte-compatible with the C (flatcc) and web clients — in particular the file
//! identifier sits at bytes 4..8 (FORMAT.md §7).
//!
//! Regenerate after a schema change (see `src/fb/README.md`):
//! ```sh
//! flatc --rust --filename-suffix _generated -o src/fb \
//!     ../schemas/tile.fbs ../schemas/tileset.fbs ../schemas/style.fbs ../schemas/model.fbs
//! ```
//! Building does not require `flatc`; only regenerating does.
//!
//! `model.fbs` includes `tile.fbs` (it reuses `Part`/`Color`), so its generated
//! code refers to the shared types through the path `crate::tile_generated`.
//! [`crate::tile_generated`] is a re-export shim that resolves that path to the
//! [`tile`] module's `arpentry::tiles` namespace.

#[path = "fb/tile_generated.rs"]
#[allow(warnings, clippy::all)]
pub mod tile;

#[path = "fb/tileset_generated.rs"]
#[allow(warnings, clippy::all)]
pub mod tileset;

#[path = "fb/style_generated.rs"]
#[allow(warnings, clippy::all)]
pub mod style;

#[path = "fb/model_generated.rs"]
#[allow(warnings, clippy::all)]
pub mod model;
