#!/usr/bin/env python3
"""Bake the MSDF font atlas for the client.

Runs msdf-atlas-gen on the Inter font to produce an MTSDF atlas
(RGB = multi-channel signed distance field for sharp fills,
A = true signed distance field for halos) and a C header with
per-glyph metrics matching the font_glyph struct in client/src/font.h.

Outputs (committed to the repository — rerun only when the font,
charset, or bake parameters change):
  client/assets/inter-msdf.png
  client/src/font_metrics.h

Requires msdf-atlas-gen (https://github.com/Chlumsky/msdf-atlas-gen)
on PATH, or set MSDF_ATLAS_GEN to the executable.
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT = os.path.join(REPO, "client/assets/Inter-SemiBold.ttf")
PNG_OUT = os.path.join(REPO, "client/assets/inter-msdf.png")
HEADER_OUT = os.path.join(REPO, "client/src/font_metrics.h")

# Must match client/src/font.h
ATLAS_SIZE = 1024
FIRST_CHAR = 0x20
LAST_CHAR = 0x24F  # end of Latin Extended-B
CHAR_COUNT = LAST_CHAR - FIRST_CHAR + 1

# Bake parameters
GLYPH_SIZE = 32  # px per em; MSDF stays sharp under magnification
PX_RANGE = 16    # distance field range in atlas px (bounds max halo width)


def main():
    tool = os.environ.get("MSDF_ATLAS_GEN") or shutil.which("msdf-atlas-gen")
    if not tool:
        sys.exit("msdf-atlas-gen not found: install it or set MSDF_ATLAS_GEN")

    with tempfile.TemporaryDirectory() as tmp:
        charset = os.path.join(tmp, "charset.txt")
        with open(charset, "w") as f:
            f.write(f"[0x{FIRST_CHAR:X}, 0x{LAST_CHAR:X}]\n")
        json_path = os.path.join(tmp, "metrics.json")

        cmd = [
            tool,
            "-font", FONT,
            "-charset", charset,
            "-type", "mtsdf",
            "-size", str(GLYPH_SIZE),
            "-pxrange", str(PX_RANGE),
            "-yorigin", "top",
            "-dimensions", str(ATLAS_SIZE), str(ATLAS_SIZE),
            "-format", "png",
            "-imageout", PNG_OUT,
            "-json", json_path,
        ]
        print(" ".join(cmd))
        subprocess.run(cmd, check=True)

        with open(json_path) as f:
            meta = json.load(f)

    atlas = meta["atlas"]
    if atlas["width"] != ATLAS_SIZE or atlas["height"] != ATLAS_SIZE:
        sys.exit(f"atlas is {atlas['width']}x{atlas['height']}, "
                 f"expected {ATLAS_SIZE}x{ATLAS_SIZE}")
    if atlas["yOrigin"] != "top":
        sys.exit("expected yOrigin=top in atlas metadata")
    size = atlas["size"]  # px per em actually used

    # font_glyph fields, indexed by codepoint - FIRST_CHAR:
    #   u0 v0 u1 v1 advance bearing_x bearing_y width height
    # bearing_y is the y-down offset of the glyph bitmap top from the
    # baseline (stb_truetype yoff convention, preserved from the old
    # runtime SDF generator).
    rows = [None] * CHAR_COUNT
    for g in meta["glyphs"]:
        cp = g["unicode"]
        if not (FIRST_CHAR <= cp <= LAST_CHAR):
            continue
        advance = g["advance"] * size
        ab, pb = g.get("atlasBounds"), g.get("planeBounds")
        if ab and pb:
            # planeBounds is em units relative to the baseline. With
            # yorigin=top both bounds are y-down, so pb top < bottom and
            # the bitmap-top offset from the baseline is pb["top"] as is.
            # Detect orientation rather than trusting it.
            if pb["top"] < pb["bottom"]:  # y-down
                bearing_y = pb["top"] * size
                v0, v1 = ab["top"] / ATLAS_SIZE, ab["bottom"] / ATLAS_SIZE
                height = ab["bottom"] - ab["top"]
            else:  # y-up
                bearing_y = -pb["top"] * size
                v0, v1 = ab["bottom"] / ATLAS_SIZE, ab["top"] / ATLAS_SIZE
                height = ab["top"] - ab["bottom"]
            rows[cp - FIRST_CHAR] = (
                ab["left"] / ATLAS_SIZE, v0,
                ab["right"] / ATLAS_SIZE, v1,
                advance,
                pb["left"] * size, bearing_y,
                ab["right"] - ab["left"], height,
            )
        else:
            # No outline (e.g. space): advance only
            rows[cp - FIRST_CHAR] = (0, 0, 0, 0, advance, 0, 0, 0, 0)

    missing = sum(1 for r in rows if r is None)
    rows = [r or (0,) * 9 for r in rows]

    with open(HEADER_OUT, "w") as f:
        f.write(
            "/* Auto-generated by scripts/generate-font-atlas.py — do not edit.\n"
            " * Per-glyph metrics for the baked MSDF atlas "
            "(client/assets/inter-msdf.png). */\n"
            "#ifndef ARPENTRY_FONT_METRICS_H\n"
            "#define ARPENTRY_FONT_METRICS_H\n\n"
            "#include \"font.h\"\n\n"
            f"#define FONT_MSDF_SIZE  {float(size):.1f}f"
            "  /* bake size in px per em */\n"
            f"#define FONT_MSDF_RANGE {float(PX_RANGE):.1f}f"
            "  /* distance field range in atlas px */\n\n"
            "static const font_glyph font_metrics[FONT_CHAR_COUNT] = {\n")
        def lit(v):
            s = "%.6g" % v
            if "." not in s and "e" not in s:
                s += ".0"
            return s + "f"

        for r in rows:
            f.write("    {%s},\n" % ", ".join(lit(v) for v in r))
        f.write("};\n\n#endif /* ARPENTRY_FONT_METRICS_H */\n")

    print(f"wrote {PNG_OUT}")
    print(f"wrote {HEADER_OUT} ({CHAR_COUNT} glyphs, {missing} missing)")


if __name__ == "__main__":
    main()
